// Copyright 2026 The Apache Software Foundation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package org.apache.tapestry5.ioc.internal.services;

/**
 * Implemented by the bridge classes generated by {@link BridgeBuilder},
 * to expose one step of an assembled pipeline.
 *
 * @since 5.10.0
 */
public interface PipelineStep
{
    /**
     * The filter invoked at this step of the pipeline.
     */
    Object getPipelineFilter();

    /**
     * What this step delegates to: the next {@link PipelineStep}, or the terminator at the end of the pipeline.
     */
    Object getPipelineNext();
}
