// Copyright 2026 The Apache Software Foundation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package org.apache.tapestry5.ioc.internal.services;

import java.util.ArrayList;
import java.util.List;

/**
 * Describes an assembled pipeline as {@code header: filter -&gt; filter -&gt; terminator}.
 *
 * <p>The {@code toString()} of the bridge classes generated by {@link BridgeBuilder} delegates here,
 * as does {@link org.apache.tapestry5.ioc.services.AssembledPipeline}.
 * @since 5.10.0
 */
public final class PipelineDescriber
{
    private static final String SEPARATOR = " -> ";

    private PipelineDescriber()
    {
    }

    /**
     * The header identifying a pipeline, ahead of its steps.
     */
    public static String header(Class<?> serviceInterface, Class<?> filterInterface)
    {
        return String.format("<PipelineBridge from %s to %s>", serviceInterface.getName(), filterInterface.getName());
    }

    /**
     * Walks the pipeline from the given step to its end, describing each filter, including the terminator.
     *
     * @param header
     *         identifies the pipeline, the steps follow it, separated by a colon
     * @param step
     *         where to start, typically the outermost bridge, but any step describes the pipeline from itself
     *         onwards
     */
    public static String describe(String header, PipelineStep step)
    {
        List<Object> steps = new ArrayList<>();

        Object current = step;

        while (current instanceof PipelineStep)
        {
            PipelineStep pipelineStep = (PipelineStep) current;

            steps.add(pipelineStep.getPipelineFilter());

            current = pipelineStep.getPipelineNext();
        }

        steps.add(current);

        return describe(header, steps);
    }

    /**
     * Describes steps that have already been collected: the filters, in the order they are invoked, followed by the
     * terminator.
     */
    public static String describe(String header, List<?> steps)
    {
        StringBuilder builder = new StringBuilder(header).append(": ");

        for (int i = 0; i < steps.size(); i++)
        {
            if (i > 0)
            {
                builder.append(SEPARATOR);
            }

            builder.append(steps.get(i));
        }

        return builder.toString();
    }
}
