name: Build Pull Request
on: pull_request

env:
  MOZ_HEADLESS: true
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  build:
    name: Build pull request
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 21 ]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # 6.0.2

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654   # 5.2.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e   # 6.1.0

      - name: Build with Gradle
        run: ./gradlew -Dci=true --no-daemon --continue build
